### ISSUE TITLE
Tail rotation constant incorrect

### ISSUE THREAD

**Issue by dwilliamson** [garycourt/murmurhash-js#3]
Please take a look at change r136 over on Google Code:

http://code.google.com/p/smhasher/source/browse/trunk/MurmurHash3.cpp?r=136

The tail rotation constant used to be 16 but was corrected to 15, above.

After that change, this code matches perfectly with the latest version with my tests.

**Comment by garycourt** [comment]
Thanks for this! I've updated the code to match.
